# credhub information
credhub_server: https://192.168.1.16:9000/info
credhub_username: credhub_client
credhub_password: secret
credhub_path: /concourse/global
credhub_skip_tls_validation: true

# pipelines repo
pipelines_repo_uri: https://github.com/patrick-huber-pivotal/credhub-sync-pipelines
pipelines_repo_branch: master
