resource_types:
- name: credhub
  type: docker-image
  source:
    repository: cfcommunity/credhub-resource

resources:
- name: credentials
  type: credhub
  source:
    server: ((credhub_server))
    username: ((credhub_username))
    password: ((credhub_password))
    path: ((credhub_path))
    skip_tls_validation: ((credhub_skip_tls_validation))

- name: pipelines-repo
  type: git
  source:
    uri: ((pipelines_repo_uri))
    branch: ((pipelines_repo_branch))
    
jobs:
- name: sync-credhub-credentials
  plan:
  - aggregate:  
    - get: credentials
      trigger: true
    - get : pipelines-repo    
  - task: sync-credhub-credentials
    file: pipelines-repo/tasks/sync-credhub-credentials/task.yml
    params:
      CREDHUB_SERVER: ((credhub_server))
      CREDHUB_CLIENT: ((credhub_username))
      CREDHUB_SECRET: ((credhub_password))
      SKIP_TLS_VALIDATION: ((credhub_skip_tls_validation))