---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

params:
    CREDHUB_SERVER:
    CREDHUB_CLIENT:
    CREDHUB_SECRET:
    SKIP_TLS_VALIDATION:
    CREDHUB_PATH:
    CREDHUB_MIRROR_PATH:
    
inputs:
- name: credentials
- name: pipelines-repo

run:
  path: pipelines-repo/tasks/sync-credhub-credentials/task.sh